### Site Settings ###
title               : alexsteeel
description         : >-
                      .NET developer.
baseurl             : "/"
repository          : alexsteeel/alexsteeel.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : alexsteeel
  image             : https://avatars0.githubusercontent.com/u/46535515?s=400&u=8ac6cadd99eb8dd13f681c6cdc76391d4bcc08b2&v=4
  email             : suchkov_as@gmail.com
  github            : alexsteeel
  instagram         : alexsteeel


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus: https-alexsteeel-github-io


### Analytics ###
analytics:
  enabled: true
  google:
    tracking_id: G-4SEVWZXNGR


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
